# Real-World Python Machine Learning Tutorial w/ Scikit Learn

In [32]:
# import necessary libraries

import pandas as pd 
from sklearn.model_selection import train_test_split

In [33]:
df = pd.read_json("D:\\Data Science\\Dataset\\Books_small_10000.json", lines=True)
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A1F2H80A1ZNN1N,B00GDM3NQC,Connie Correll,"[0, 0]","I bought both boxed sets, books 1-5. Really a...",5,Can't stop reading!,1390435200,"01 23, 2014"
1,AI3DRTKCSK4KX,B00A5MREAM,Grandma,"[0, 0]",I enjoyed this short book. But it was way way ...,3,A leaf on the wind of all hallows,1399593600,"05 9, 2014"
2,A3KAKFHY9DAC8A,0446547573,"toobusyreading ""Inspired Kathy""","[1, 1]",I love Nicholas Sparks. I&#8217;ve read everyt...,4,Great writing from Nicholas Sparks.,1404518400,"07 5, 2014"
3,ATYBCYD6BIXVL,0955809215,Chrissie,"[0, 0]",I really enjoyed this adventure and look forwa...,4,great,1389225600,"01 9, 2014"
4,A17K95SEU3J68U,0991500776,"Sirde ""artist761""","[0, 0]",It was a decent read.. typical story line. Not...,3,It was a decent read.. typical story line ...,1404864000,"07 9, 2014"

In [34]:
new_df =df[["reviewText","overall"]]
new_df.head()

                                          reviewText  overall
0  I bought both boxed sets, books 1-5.  Really a...        5
1  I enjoyed this short book. But it was way way ...        3
2  I love Nicholas Sparks. I&#8217;ve read everyt...        4
3  I really enjoyed this adventure and look forwa...        4
4  It was a decent read.. typical story line. Not...        3

In [35]:
new_df["overall"].isnull().sum()

0

In [75]:
X = new_df.copy().drop(new_df["overall"])
y =new_df["overall"]

print(X.shape)
print(y.shape)

X_train, y_train, X_test, y_test = train_test_split(X,y, test_size= 0.33, random_state = 42)

(9995, 2)
(10000,)

ValueError: Found input variables with inconsistent numbers of samples: [9995, 10000]

In [74]:
y.shape

(10000,)

In [72]:
new_df.tail(50)

                                             reviewText  overall
9950  This one is written very well, but it's still ...        4
9951  I am still using this book and will go back to...        5
9952  This is marketed as a vampire book, and I do h...        4
9953  Anyone who may have a remote interest in the p...        5
9954  Like most schools boys, I had heard of the Gre...        5
9955  I learned a lot about Italy's history. History...        5
9956  keeps it alive and replaceable. I was surprise...        5
9957  We know carbs are bad for us, especially white...        5
9958  This is a series of three childhood friends an...        4
9959  There are six short stories in this novel.  Si...        5
9960  GREAT SERIES!!  Do not hesitate on this series...        5
9961  Echo, Echo, Echo.... You beautiful, cocky, swe...        5
9962  Been waiting impatiently for this book to come...        4
9963  I really enjoyed this book.. With social netwo...        5
9964  The short version of why Hellboy&#8217;s in he...        3
9965  Easy to follow recipes were also very tasty. A...        5
9966  If you find yourself needing to lose ALOT of w...        3
9967  Great intro to the &#34;Chaos Walking&#34; tri...        5
9968  Well worth the time to read.  I love this fami...        5
9969  Fascinating account of the history of how the ...        5
9970  Another great collection of short stories from...        5
9971  The story was engaging, not a predictable solu...        4
9972  This is one of the best novels I've read in a ...        5
9973  really loved this book , cant wait to read mor...        5
9974  The Guardian DukeBy: Jamie Carie5 starsReviewe...        5
9975  A page-turning who-dunnit, memorable character...        5
9976  The trials and battles of the first BLACK Pres...        5
9977  It w a s just an okay book until the big surpr...        2
9978  I'm at Chapter 20 of this book, and lovin' eve...        5
9979  This author has a good imagination and good me...        3
9980  This series of 3 stories are great individuall...        5
9981  I am very picky when it comes to what I like t...        1
9982  *I received a free copy of this book to read a...        2
9983  Loved the book and the twist like he was a pri...        5
9984  Having this book toted as a YA series on Amazo...        1
9985  Cat has been pressing her husband of ten years...        4
9986  I found this a delightful story.  A modern ver...        5
9987  I received this book from the author for an ho...        4
9988  Roberts does not disappoint in the second book...        5
9989  I honestly wasn&#8217;t sure what I was gettin...        5
9990  James Patterson delivers again, fast read, goo...        5
9991  The quide helped with a lot of event and item ...        4
9992  Intense and not for the faint of heart, Craig ...        5
9993  I've tried to start this graphic novel a coupl...        2
9994  Not so Much this.  There is a less genuine res...        2
9995  The whole series was great!  Melody is a fanta...        5
9996  I didn't thing that much of this book.  I am a...        3
9997  It is an emotional TRIP to the past with Trip ...        5
9998  This definitely got under my veins whereby I h...        5
9999  Highly recommend this entire trilogy. It is ve...        4

In [29]:
class Sentiment:
    NEGATIVE = 'NEGATIVE'
    NEUTRAL = 'NEUTRAL'
    POSITIVE = 'POSITIVE'

class Review:
    def __init__(self, text , score):
        self.text = text
        self.score = score
        self.sentiment = self.get_sentiment()
        
    def get_sentiment(self):
        if self.score <= 2:
            return Sentiment.NEGATIVE
        elif self.score == 3:
            return Sentiment.NEUTRAL
        else:
            return Sentiment.POSITIVE